@DocFlow.AuthService_HostAddress = http://localhost:5295

###
POST {{DocFlow.AuthService_HostAddress}}/api/auth/register/
Content-Type: application/json
Accept: application/json
{
  "email": "jorman@example.com",
  "password": "password123hashed!",
  "confirmPassword": "password123hashed!",
  "username": "user"
}
###
POST {{DocFlow.AuthService_HostAddress}}/api/auth/login/
Content-Type: application/json
accept: application/json
{
    "email": "jorman@example.com",
    "password": "password123hashed!"
}
###
GET {{DocFlow.AuthService_HostAddress}}/api/auth/me/
Content-type: application/json
Accept: application/json
{
    "id":"67e700a9f956f19997b31ea0",
    "email":"jorman@example.com",
    "role":"User"
}
