@DocFlow.AuthService_HostAddress = http://localhost:5295

GET {{DocFlow.AuthService_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{DocFlow.AuthService_HostAddress}}/api/auth/register/
Content-Type: application/json
Accept: application/json
{
  "email": "jorman@example.com",
  "password": "password123hashed!",
  "confirmPassword": "password123hashed!",
  "username": "user"
}
###
POST {{DocFlow.AuthService_HostAddress}}/api/auth/login/
Content-Type: application/json
accept: application/json
{
    "email": "jorman@example.com",
    "password": "password123hashed!"
}
